version: '3'
services:
  postgresql:
    image: postgres
    restart: unless-stopped
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pg-data:
    driver: local